tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_cs_fixer:
            config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
    php_code_sniffer:
            config:
                standard: "PSR2"

filter:
    excluded_paths:
        - 'tests/*'

build:
    environment:
        php:
            version: 5.5

